name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - name: 🦑 Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_achievements: yes
          plugin_achievements_display: compact

      - name: 🦑 General
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_discussions: yes
          
      - name: Indepth analysis 
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes

